####### "This script can be run by {$ dvc repro} -> creates dvc.lock file"

stages:
  load_data:
    cmd: python3 src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - pseudo_s3_bucket/winequality.csv
    outs:
    - data/raw/winequality.csv

  split_data:
    cmd: python3 src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv 

  train_and_evaluate:
    cmd: python3 src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    # metrics:
    # - reports/scores.json:
    #     cache: false
    # - reports/params.json:
    #     cache: false
    # outs:
    # - saved_models/model.joblib

    ### Commented above for using MLFlow

  log_production_model:
    cmd: python3 src/log_production_model.py --config=params.yaml
    deps:
    - src/log_production_model.py